[project]
name = "order-processing-fraud-detection"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi (>=0.141.1,<0.142.0)",
    "uvicorn[standard] (>=0.52.4,<0.53.0)",
    "aiokafka (>=0.14.0,<0.15.0)",
    "pydantic (>=2.13.5,<3.0.0)",
    "pydantic-settings (>=2.15.0,<3.0.0)",
    "ruff (>=0.16.5,<0.17.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
