apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: api
        image: order-api:v1
        ports:
        - containerPort: 8000
        env:
        - name: KAFKA_SERVER
          value: "kafka.default.svc.cluster.local:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: order-api-service
spec:
  type: ClusterIP
  selector:
    app: order-api
  ports:
  - port: 8000
    targetPort: 8000