apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-consumer-deployment
spec:
  replicas: 0 # Scaled dynamically by KEDA
  selector:
    matchLabels:
      app: order-consumer
  template:
    metadata:
      labels:
        app: order-consumer
    spec:
      containers:
      - name: consumer
        image: order-consumer:v1
        env:
        - name: KAFKA_SERVER
          value: "kafka.default.svc.cluster.local:9092"